const countries = [
    { mobile_code: "93", value: "Afghanistan", code: "AF" },
    { mobile_code: "358", value: "Aland Islands", code: "AX" },
    { mobile_code: "355", value: "Albania", code: "AL" },
    { mobile_code: "213", value: "Algeria", code: "DZ" },
    { mobile_code: "1684", value: "AmericanSamoa", code: "AS" },
    { mobile_code: "376", value: "Andorra", code: "AD" },
    { mobile_code: "244", value: "Angola", code: "AO" },
    { mobile_code: "1264", value: "Anguilla", code: "AI" },
    { mobile_code: "672", value: "Antarctica", code: "AQ" },
    { mobile_code: "1268", value: "Antigua and Barbuda", code: "AG" },
    { mobile_code: "54", value: "Argentina", code: "AR" },
    { mobile_code: "374", value: "Armenia", code: "AM" },
    { mobile_code: "297", value: "Aruba", code: "AW" },
    { mobile_code: "61", value: "Australia", code: "AU" },
    { mobile_code: "43", value: "Austria", code: "AT" },
    { mobile_code: "994", value: "Azerbaijan", code: "AZ" },
    { mobile_code: "1242", value: "Bahamas", code: "BS" },
    { mobile_code: "973", value: "Bahrain", code: "BH" },
    { mobile_code: "880", value: "Bangladesh", code: "BD" },
    { mobile_code: "1246", value: "Barbados", code: "BB" },
    { mobile_code: "375", value: "Belarus", code: "BY" },
    { mobile_code: "32", value: "Belgium", code: "BE" },
    { mobile_code: "501", value: "Belize", code: "BZ" },
    { mobile_code: "229", value: "Benin", code: "BJ" },
    { mobile_code: "1441", value: "Bermuda", code: "BM" },
    { mobile_code: "975", value: "Bhutan", code: "BT" },
    { mobile_code: "591", value: "Plurinational State of Bolivia", code: "BO" },
    { mobile_code: "387", value: "Bosnia and Herzegovina", code: "BA" },
    { mobile_code: "267", value: "Botswana", code: "BW" },
    { mobile_code: "55", value: "Brazil", code: "BR" },
    { mobile_code: "246", value: "British Indian Ocean Territory", code: "IO" },
    { mobile_code: "673", value: "Brunei Darussalam", code: "BN" },
    { mobile_code: "359", value: "Bulgaria", code: "BG" },
    { mobile_code: "226", value: "Burkina Faso", code: "BF" },
    { mobile_code: "257", value: "Burundi", code: "BI" },
    { mobile_code: "855", value: "Cambodia", code: "KH" },
    { mobile_code: "237", value: "Cameroon", code: "CM" },
    { mobile_code: "1", value: "Canada", code: "CA" },
    { mobile_code: "238", value: "Cape Verde", code: "CV" },
    { mobile_code: "345", value: "Cayman Islands", code: "KY" },
    { mobile_code: "236", value: "Central African Republic", code: "CF" },
    { mobile_code: "235", value: "Chad", code: "TD" },
    { mobile_code: "56", value: "Chile", code: "CL" },
    { mobile_code: "86", value: "China", code: "CN" },
    { mobile_code: "61", value: "Christmas Island", code: "CX" },
    { mobile_code: "61", value: "Cocos (Keeling) Islands", code: "CC" },
    { mobile_code: "57", value: "Colombia", code: "CO" },
    { mobile_code: "269", value: "Comoros", code: "KM" },
    { mobile_code: "242", value: "Congo", code: "CG" },
    { mobile_code: "243", value: "The Democratic Republic of the Congo", code: "CD" },
    { mobile_code: "682", value: "Cook Islands", code: "CK" },
    { mobile_code: "506", value: "Costa Rica", code: "CR" },
    { mobile_code: "225", value: "Cote d'Ivoire", code: "CI" },
    { mobile_code: "385", value: "Croatia", code: "HR" },
    { mobile_code: "53", value: "Cuba", code: "CU" },
    { mobile_code: "357", value: "Cyprus", code: "CY" },
    { mobile_code: "420", value: "Czech Republic", code: "CZ" },
    { mobile_code: "45", value: "Denmark", code: "DK" },
    { mobile_code: "253", value: "Djibouti", code: "DJ" },
    { mobile_code: "1767", value: "Dominica", code: "DM" },
    { mobile_code: "1849", value: "Dominican Republic", code: "DO" },
    { mobile_code: "593", value: "Ecuador", code: "EC" },
    { mobile_code: "20", value: "Egypt", code: "EG" },
    { mobile_code: "503", value: "El Salvador", code: "SV" },
    { mobile_code: "240", value: "Equatorial Guinea", code: "GQ" },
    { mobile_code: "291", value: "Eritrea", code: "ER" },
    { mobile_code: "372", value: "Estonia", code: "EE" },
    { mobile_code: "251", value: "Ethiopia", code: "ET" },
    { mobile_code: "500", value: "Falkland Islands (Malvinas)", code: "FK" },
    { mobile_code: "298", value: "Faroe Islands", code: "FO" },
    { mobile_code: "679", value: "Fiji", code: "FJ" },
    { mobile_code: "358", value: "Finland", code: "FI" },
    { mobile_code: "33", value: "France", code: "FR" },
    { mobile_code: "594", value: "French Guiana", code: "GF" },
    { mobile_code: "689", value: "French Polynesia", code: "PF" },
    { mobile_code: "241", value: "Gabon", code: "GA" },
    { mobile_code: "220", value: "Gambia", code: "GM" },
    { mobile_code: "995", value: "Georgia", code: "GE" },
    { mobile_code: "49", value: "Germany", code: "DE" },
    { mobile_code: "233", value: "Ghana", code: "GH" },
    { mobile_code: "350", value: "Gibraltar", code: "GI" },
    { mobile_code: "30", value: "Greece", code: "GR" },
    { mobile_code: "299", value: "Greenland", code: "GL" },
    { mobile_code: "1473", value: "Grenada", code: "GD" },
    { mobile_code: "590", value: "Guadeloupe", code: "GP" },
    { mobile_code: "1671", value: "Guam", code: "GU" },
    { mobile_code: "502", value: "Guatemala", code: "GT" },
    { mobile_code: "44", value: "Guernsey", code: "GG" },
    { mobile_code: "224", value: "Guinea", code: "GN" },
    { mobile_code: "245", value: "Guinea-Bissau", code: "GW" },
    { mobile_code: "595", value: "Guyana", code: "GY" },
    { mobile_code: "509", value: "Haiti", code: "HT" },
    { mobile_code: "379", value: "Holy See (Vatican City State)", code: "VA" },
    { mobile_code: "504", value: "Honduras", code: "HN" },
    { mobile_code: "852", value: "Hong Kong", code: "HK" },
    { mobile_code: "36", value: "Hungary", code: "HU" },
    { mobile_code: "354", value: "Iceland", code: "IS" },
    { mobile_code: "91", value: "India", code: "IN" },
    { mobile_code: "62", value: "Indonesia", code: "ID" },
    { mobile_code: "98", value: "Iran, Islamic Republic of Persian Gulf", code: "IR" },
    { mobile_code: "964", value: "Iraq", code: "IQ" },
    { mobile_code: "353", value: "Ireland", code: "IE" },
    { mobile_code: "44", value: "Isle of Man", code: "IM" },
    { mobile_code: "972", value: "Israel", code: "IL" },
    { mobile_code: "39", value: "Italy", code: "IT" },
    { mobile_code: "1876", value: "Jamaica", code: "JM" },
    { mobile_code: "81", value: "Japan", code: "JP" },
    { mobile_code: "44", value: "Jersey", code: "JE" },
    { mobile_code: "962", value: "Jordan", code: "JO" },
    { mobile_code: "77", value: "Kazakhstan", code: "KZ" },
    { mobile_code: "254", value: "Kenya", code: "KE" },
    { mobile_code: "686", value: "Kiribati", code: "KI" },
    { mobile_code: "850", value: "Democratic People's Republic of Korea", code: "KP" },
    { mobile_code: "82", value: "Republic of South Korea", code: "KR" },
    { mobile_code: "965", value: "Kuwait", code: "KW" },
    { mobile_code: "996", value: "Kyrgyzstan", code: "KG" },
    { mobile_code: "856", value: "Laos", code: "LA" },
    { mobile_code: "371", value: "Latvia", code: "LV" },
    { mobile_code: "961", value: "Lebanon", code: "LB" },
    { mobile_code: "266", value: "Lesotho", code: "LS" },
    { mobile_code: "231", value: "Liberia", code: "LR" },
    { mobile_code: "218", value: "Libyan Arab Jamahiriya", code: "LY" },
    { mobile_code: "423", value: "Liechtenstein", code: "LI" },
    { mobile_code: "370", value: "Lithuania", code: "LT" },
    { mobile_code: "352", value: "Luxembourg", code: "LU" },
    { mobile_code: "853", value: "Macao", code: "MO" },
    { mobile_code: "389", value: "Macedonia", code: "MK" },
    { mobile_code: "261", value: "Madagascar", code: "MG" },
    { mobile_code: "265", value: "Malawi", code: "MW" },
    { mobile_code: "60", value: "Malaysia", code: "MY" },
    { mobile_code: "960", value: "Maldives", code: "MV" },
    { mobile_code: "223", value: "Mali", code: "ML" },
    { mobile_code: "356", value: "Malta", code: "MT" },
    { mobile_code: "692", value: "Marshall Islands", code: "MH" },
    { mobile_code: "596", value: "Martinique", code: "MQ" },
    { mobile_code: "222", value: "Mauritania", code: "MR" },
    { mobile_code: "230", value: "Mauritius", code: "MU" },
    { mobile_code: "262", value: "Mayotte", code: "YT" },
    { mobile_code: "52", value: "Mexico", code: "MX" },
    { mobile_code: "691", value: "Federated States of Micronesia", code: "FM" },
    { mobile_code: "373", value: "Moldova", code: "MD" },
    { mobile_code: "377", value: "Monaco", code: "MC" },
    { mobile_code: "976", value: "Mongolia", code: "MN" },
    { mobile_code: "382", value: "Montenegro", code: "ME" },
    { mobile_code: "1664", value: "Montserrat", code: "MS" },
    { mobile_code: "212", value: "Morocco", code: "MA" },
    { mobile_code: "258", value: "Mozambique", code: "MZ" },
    { mobile_code: "95", value: "Myanmar", code: "MM" },
    { mobile_code: "264", value: "Namibia", code: "NA" },
    { mobile_code: "674", value: "Nauru", code: "NR" },
    { mobile_code: "977", value: "Nepal", code: "NP" },
    { mobile_code: "31", value: "Netherlands", code: "NL" },
    { mobile_code: "599", value: "Netherlands Antilles", code: "AN" },
    { mobile_code: "687", value: "New Caledonia", code: "NC" },
    { mobile_code: "64", value: "New Zealand", code: "NZ" },
    { mobile_code: "505", value: "Nicaragua", code: "NI" },
    { mobile_code: "227", value: "Niger", code: "NE" },
    { mobile_code: "234", value: "Nigeria", code: "NG" },
    { mobile_code: "683", value: "Niue", code: "NU" },
    { mobile_code: "672", value: "Norfolk Island", code: "NF" },
    { mobile_code: "1670", value: "Northern Mariana Islands", code: "MP" },
    { mobile_code: "47", value: "Norway", code: "NO" },
    { mobile_code: "968", value: "Oman", code: "OM" },
    { mobile_code: "92", value: "Pakistan", code: "PK" },
    { mobile_code: "680", value: "Palau", code: "PW" },
    { mobile_code: "970", value: "Palestinian Territory", code: "PS" },
    { mobile_code: "507", value: "Panama", code: "PA" },
    { mobile_code: "675", value: "Papua New Guinea", code: "PG" },
    { mobile_code: "595", value: "Paraguay", code: "PY" },
    { mobile_code: "51", value: "Peru", code: "PE" },
    { mobile_code: "63", value: "Philippines", code: "PH" },
    { mobile_code: "872", value: "Pitcairn", code: "PN" },
    { mobile_code: "48", value: "Poland", code: "PL" },
    { mobile_code: "351", value: "Portugal", code: "PT" },
    { mobile_code: "1939", value: "Puerto Rico", code: "PR" },
    { mobile_code: "974", value: "Qatar", code: "QA" },
    { mobile_code: "40", value: "Romania", code: "RO" },
    { mobile_code: "7", value: "Russia", code: "RU" },
    { mobile_code: "250", value: "Rwanda", code: "RW" },
    { mobile_code: "262", value: "Reunion", code: "RE" },
    { mobile_code: "590", value: "Saint Barthelemy", code: "BL" },
    { mobile_code: "290", value: "Saint Helena", code: "SH" },
    { mobile_code: "1869", value: "Saint Kitts and Nevis", code: "KN" },
    { mobile_code: "1758", value: "Saint Lucia", code: "LC" },
    { mobile_code: "590", value: "Saint Martin", code: "MF" },
    { mobile_code: "508", value: "Saint Pierre and Miquelon", code: "PM" },
    { mobile_code: "1784", value: "Saint Vincent and the Grenadines", code: "VC" },
    { mobile_code: "685", value: "Samoa", code: "WS" },
    { mobile_code: "378", value: "San Marino", code: "SM" },
    { mobile_code: "239", value: "Sao Tome and Principe", code: "ST" },
    { mobile_code: "966", value: "Saudi Arabia", code: "SA" },
    { mobile_code: "221", value: "Senegal", code: "SN" },
    { mobile_code: "381", value: "Serbia", code: "RS" },
    { mobile_code: "248", value: "Seychelles", code: "SC" },
    { mobile_code: "232", value: "Sierra Leone", code: "SL" },
    { mobile_code: "65", value: "Singapore", code: "SG" },
    { mobile_code: "421", value: "Slovakia", code: "SK" },
    { mobile_code: "386", value: "Slovenia", code: "SI" },
    { mobile_code: "677", value: "Solomon Islands", code: "SB" },
    { mobile_code: "252", value: "Somalia", code: "SO" },
    { mobile_code: "27", value: "South Africa", code: "ZA" },
    { mobile_code: "211", value: "South Sudan", code: "SS" },
    { mobile_code: "500", value: "South Georgia and the South Sandwich Islands", code: "GS" },
    { mobile_code: "34", value: "Spain", code: "ES" },
    { mobile_code: "94", value: "Sri Lanka", code: "LK" },
    { mobile_code: "249", value: "Sudan", code: "SD" },
    { mobile_code: "597", value: "Suricountry", code: "SR" },
    { mobile_code: "47", value: "Svalbard and Jan Mayen", code: "SJ" },
    { mobile_code: "268", value: "Swaziland", code: "SZ" },
    { mobile_code: "46", value: "Sweden", code: "SE" },
    { mobile_code: "41", value: "Switzerland", code: "CH" },
    { mobile_code: "963", value: "Syrian Arab Republic", code: "SY" },
    { mobile_code: "886", value: "Taiwan", code: "TW" },
    { mobile_code: "992", value: "Tajikistan", code: "TJ" },
    { mobile_code: "255", value: "Tanzania", code: "TZ" },
    { mobile_code: "66", value: "Thailand", code: "TH" },
    { mobile_code: "670", value: "Timor-Leste", code: "TL" },
    { mobile_code: "228", value: "Togo", code: "TG" },
    { mobile_code: "690", value: "Tokelau", code: "TK" },
    { mobile_code: "676", value: "Tonga", code: "TO" },
    { mobile_code: "1868", value: "Trinidad and Tobago", code: "TT" },
    { mobile_code: "216", value: "Tunisia", code: "TN" },
    { mobile_code: "90", value: "Turkey", code: "TR" },
    { mobile_code: "993", value: "Turkmenistan", code: "TM" },
    { mobile_code: "1649", value: "Turks and Caicos Islands", code: "TC" },
    { mobile_code: "688", value: "Tuvalu", code: "TV" },
    { mobile_code: "256", value: "Uganda", code: "UG" },
    { mobile_code: "380", value: "Ukraine", code: "UA" },
    { mobile_code: "971", value: "United Arab Emirates", code: "AE" },
    { mobile_code: "44", value: "United Kingdom", code: "GB" },
    { mobile_code: "1", value: "United States", code: "US" },
    { mobile_code: "598", value: "Uruguay", code: "UY" },
    { mobile_code: "998", value: "Uzbekistan", code: "UZ" },
    { mobile_code: "678", value: "Vanuatu", code: "VU" },
    { mobile_code: "58", value: "Venezuela", code: "VE" },
    { mobile_code: "84", value: "Vietnam", code: "VN" },
    { mobile_code: "1284", value: "British Virgin Islands", code: "VG" },
    { mobile_code: "1340", value: "U.S. Virgin Islands", code: "VI" },
    { mobile_code: "681", value: "Wallis and Futuna", code: "WF" },
    { mobile_code: "967", value: "Yemen", code: "YE" },
    { mobile_code: "260", value: "Zambia", code: "ZM" },
    { mobile_code: "263", value: "Zimbabwe", code: "ZW" },
]

export default countries;
