import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1748734179142 implements MigrationInterface {
    name = 'Init1748734179142'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`admins\` CHANGE \`role\` \`role\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`admins\` CHANGE \`referralCode\` \`referralCode\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`locations\` CHANGE \`latitude\` \`latitude\` float NULL`);
        await queryRunner.query(`ALTER TABLE \`locations\` CHANGE \`longitude\` \`longitude\` float NULL`);
        await queryRunner.query(`ALTER TABLE \`locations\` CHANGE \`notes\` \`notes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`food_items\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`food_items\` CHANGE \`discountedPrice\` \`discountedPrice\` float NULL`);
        await queryRunner.query(`ALTER TABLE \`food_items\` CHANGE \`imageUrl\` \`imageUrl\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`food_items\` CHANGE \`preparationTimeMinutes\` \`preparationTimeMinutes\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`food_items\` CHANGE \`variants\` \`variants\` longtext NULL`);
        await queryRunner.query(`ALTER TABLE \`food_items\` CHANGE \`addons\` \`addons\` longtext NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP FOREIGN KEY \`FK_9a6f051e66982b5f0318981bcaa\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP FOREIGN KEY \`FK_fe8e7d37475de7eb2f8f83a6da0\``);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`imageUrl\` \`imageUrl\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`parentId\` \`parentId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`restaurantId\` \`restaurantId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`deposit_withdrawals\` DROP FOREIGN KEY \`FK_403c844f01b564431506c61e889\``);
        await queryRunner.query(`ALTER TABLE \`deposit_withdrawals\` DROP FOREIGN KEY \`FK_2b4026614da4637eba86e441868\``);
        await queryRunner.query(`ALTER TABLE \`deposit_withdrawals\` CHANGE \`payment_id\` \`payment_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`deposit_withdrawals\` CHANGE \`transaction_id\` \`transaction_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`deposit_withdrawals\` CHANGE \`rate\` \`rate\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`deposit_withdrawals\` CHANGE \`user_id\` \`user_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_145532db85752b29c57d2b7b1f1\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`orderId\` \`orderId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`variants\` \`variants\` longtext NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`addons\` \`addons\` longtext NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`notes\` \`notes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`order_id\` \`order_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_a922b820eeef29ac1c6800e826a\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_85fdda5fcce2f397ef8f117a2c6\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_141cb5f1928caf8b0e77cb8bd66\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_6284f0f60e4cb96c12ff96f0f15\``);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`restaurantId\` \`restaurantId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`deliveryId\` \`deliveryId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`couponId\` \`couponId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`specialInstructions\` \`specialInstructions\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`deliveryAddress\` \`deliveryAddress\` longtext NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`user_id\` \`user_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`restaurant_id\` \`restaurant_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`delivery_id\` \`delivery_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`coupon_id\` \`coupon_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_8110309ac51ed55a91d28625b88\``);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`parentId\` \`parentId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`deliveryAddresses\` \`deliveryAddresses\` longtext NULL`);
        await queryRunner.query(`ALTER TABLE \`transactions\` DROP FOREIGN KEY \`FK_e9acc6efa76de013e8c1553ed2b\``);
        await queryRunner.query(`ALTER TABLE \`transactions\` CHANGE \`detail\` \`detail\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`transactions\` CHANGE \`reference_id\` \`reference_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`transactions\` CHANGE \`user_id\` \`user_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`login_activity\` DROP FOREIGN KEY \`FK_28aab163e727fb7ddbb9f07c485\``);
        await queryRunner.query(`ALTER TABLE \`login_activity\` DROP FOREIGN KEY \`FK_6ab7239f4c14afacea611ea065f\``);
        await queryRunner.query(`ALTER TABLE \`login_activity\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`login_activity\` CHANGE \`ip\` \`ip\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`login_activity\` CHANGE \`browser\` \`browser\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`login_activity\` CHANGE \`device\` \`device\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`login_activity\` CHANGE \`os\` \`os\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`login_activity\` CHANGE \`details\` \`details\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`login_activity\` CHANGE \`adminId\` \`adminId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_messages\` DROP FOREIGN KEY \`FK_74adf60fffd02e8c754b882b1d3\``);
        await queryRunner.query(`ALTER TABLE \`user_messages\` CHANGE \`sender_id\` \`sender_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`payment_gateways\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`payment_gateways\` CHANGE \`config\` \`config\` longtext NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD CONSTRAINT \`FK_9a6f051e66982b5f0318981bcaa\` FOREIGN KEY (\`parentId\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD CONSTRAINT \`FK_fe8e7d37475de7eb2f8f83a6da0\` FOREIGN KEY (\`restaurantId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`deposit_withdrawals\` ADD CONSTRAINT \`FK_2b4026614da4637eba86e441868\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`deposit_withdrawals\` ADD CONSTRAINT \`FK_403c844f01b564431506c61e889\` FOREIGN KEY (\`transaction_id\`) REFERENCES \`transactions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_145532db85752b29c57d2b7b1f1\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_a922b820eeef29ac1c6800e826a\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_85fdda5fcce2f397ef8f117a2c6\` FOREIGN KEY (\`restaurant_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_141cb5f1928caf8b0e77cb8bd66\` FOREIGN KEY (\`delivery_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_6284f0f60e4cb96c12ff96f0f15\` FOREIGN KEY (\`coupon_id\`) REFERENCES \`coupons\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_8110309ac51ed55a91d28625b88\` FOREIGN KEY (\`parentId\`) REFERENCES \`admins\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transactions\` ADD CONSTRAINT \`FK_e9acc6efa76de013e8c1553ed2b\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`login_activity\` ADD CONSTRAINT \`FK_28aab163e727fb7ddbb9f07c485\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`login_activity\` ADD CONSTRAINT \`FK_6ab7239f4c14afacea611ea065f\` FOREIGN KEY (\`adminId\`) REFERENCES \`admins\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_messages\` ADD CONSTRAINT \`FK_74adf60fffd02e8c754b882b1d3\` FOREIGN KEY (\`sender_id\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`user_messages\` DROP FOREIGN KEY \`FK_74adf60fffd02e8c754b882b1d3\``);
        await queryRunner.query(`ALTER TABLE \`login_activity\` DROP FOREIGN KEY \`FK_6ab7239f4c14afacea611ea065f\``);
        await queryRunner.query(`ALTER TABLE \`login_activity\` DROP FOREIGN KEY \`FK_28aab163e727fb7ddbb9f07c485\``);
        await queryRunner.query(`ALTER TABLE \`transactions\` DROP FOREIGN KEY \`FK_e9acc6efa76de013e8c1553ed2b\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_8110309ac51ed55a91d28625b88\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_6284f0f60e4cb96c12ff96f0f15\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_141cb5f1928caf8b0e77cb8bd66\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_85fdda5fcce2f397ef8f117a2c6\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_a922b820eeef29ac1c6800e826a\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_145532db85752b29c57d2b7b1f1\``);
        await queryRunner.query(`ALTER TABLE \`deposit_withdrawals\` DROP FOREIGN KEY \`FK_403c844f01b564431506c61e889\``);
        await queryRunner.query(`ALTER TABLE \`deposit_withdrawals\` DROP FOREIGN KEY \`FK_2b4026614da4637eba86e441868\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP FOREIGN KEY \`FK_fe8e7d37475de7eb2f8f83a6da0\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP FOREIGN KEY \`FK_9a6f051e66982b5f0318981bcaa\``);
        await queryRunner.query(`ALTER TABLE \`payment_gateways\` CHANGE \`config\` \`config\` longtext NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payment_gateways\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_messages\` CHANGE \`sender_id\` \`sender_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_messages\` ADD CONSTRAINT \`FK_74adf60fffd02e8c754b882b1d3\` FOREIGN KEY (\`sender_id\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`login_activity\` CHANGE \`adminId\` \`adminId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`login_activity\` CHANGE \`details\` \`details\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`login_activity\` CHANGE \`os\` \`os\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`login_activity\` CHANGE \`device\` \`device\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`login_activity\` CHANGE \`browser\` \`browser\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`login_activity\` CHANGE \`ip\` \`ip\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`login_activity\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`login_activity\` ADD CONSTRAINT \`FK_6ab7239f4c14afacea611ea065f\` FOREIGN KEY (\`adminId\`) REFERENCES \`admins\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`login_activity\` ADD CONSTRAINT \`FK_28aab163e727fb7ddbb9f07c485\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transactions\` CHANGE \`user_id\` \`user_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`transactions\` CHANGE \`reference_id\` \`reference_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`transactions\` CHANGE \`detail\` \`detail\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`transactions\` ADD CONSTRAINT \`FK_e9acc6efa76de013e8c1553ed2b\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`deliveryAddresses\` \`deliveryAddresses\` longtext NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`parentId\` \`parentId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_8110309ac51ed55a91d28625b88\` FOREIGN KEY (\`parentId\`) REFERENCES \`admins\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`coupon_id\` \`coupon_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`delivery_id\` \`delivery_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`restaurant_id\` \`restaurant_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`user_id\` \`user_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`deliveryAddress\` \`deliveryAddress\` longtext NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`specialInstructions\` \`specialInstructions\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`couponId\` \`couponId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`deliveryId\` \`deliveryId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`restaurantId\` \`restaurantId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_6284f0f60e4cb96c12ff96f0f15\` FOREIGN KEY (\`coupon_id\`) REFERENCES \`coupons\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_141cb5f1928caf8b0e77cb8bd66\` FOREIGN KEY (\`delivery_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_85fdda5fcce2f397ef8f117a2c6\` FOREIGN KEY (\`restaurant_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_a922b820eeef29ac1c6800e826a\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`order_id\` \`order_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`notes\` \`notes\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`addons\` \`addons\` longtext NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`variants\` \`variants\` longtext NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`orderId\` \`orderId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_145532db85752b29c57d2b7b1f1\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`deposit_withdrawals\` CHANGE \`user_id\` \`user_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`deposit_withdrawals\` CHANGE \`rate\` \`rate\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`deposit_withdrawals\` CHANGE \`transaction_id\` \`transaction_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`deposit_withdrawals\` CHANGE \`payment_id\` \`payment_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`deposit_withdrawals\` ADD CONSTRAINT \`FK_2b4026614da4637eba86e441868\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`deposit_withdrawals\` ADD CONSTRAINT \`FK_403c844f01b564431506c61e889\` FOREIGN KEY (\`transaction_id\`) REFERENCES \`transactions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`restaurantId\` \`restaurantId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`parentId\` \`parentId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`imageUrl\` \`imageUrl\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD CONSTRAINT \`FK_fe8e7d37475de7eb2f8f83a6da0\` FOREIGN KEY (\`restaurantId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD CONSTRAINT \`FK_9a6f051e66982b5f0318981bcaa\` FOREIGN KEY (\`parentId\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`food_items\` CHANGE \`addons\` \`addons\` longtext NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`food_items\` CHANGE \`variants\` \`variants\` longtext NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`food_items\` CHANGE \`preparationTimeMinutes\` \`preparationTimeMinutes\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`food_items\` CHANGE \`imageUrl\` \`imageUrl\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`food_items\` CHANGE \`discountedPrice\` \`discountedPrice\` float(12) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`food_items\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`locations\` CHANGE \`notes\` \`notes\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`locations\` CHANGE \`longitude\` \`longitude\` float(12) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`locations\` CHANGE \`latitude\` \`latitude\` float(12) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`admins\` CHANGE \`referralCode\` \`referralCode\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`admins\` CHANGE \`role\` \`role\` varchar(255) NULL DEFAULT 'NULL'`);
    }

}
