import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1748621180895 implements MigrationInterface {
    name = 'Init1748621180895'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`admins\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`email\` varchar(255) NOT NULL, \`password\` varchar(255) NOT NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`role\` varchar(255) NULL, \`referralCode\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_051db7d37d478a69a7432df147\` (\`email\`), UNIQUE INDEX \`IDX_b4585db4f7fe5bdf537bd81861\` (\`referralCode\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`locations\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userId\` int NOT NULL, \`address\` varchar(255) NOT NULL, \`city\` varchar(100) NOT NULL, \`state\` varchar(100) NOT NULL, \`postalCode\` varchar(20) NOT NULL, \`country\` varchar(100) NOT NULL, \`latitude\` float NULL, \`longitude\` float NULL, \`type\` enum ('home', 'work', 'other') NOT NULL DEFAULT 'home', \`isPrimary\` tinyint NOT NULL DEFAULT 0, \`notes\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`food_items\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(100) NOT NULL, \`description\` text NULL, \`price\` float NOT NULL, \`discountedPrice\` float NULL, \`imageUrl\` text NULL, \`isAvailable\` tinyint NOT NULL DEFAULT 1, \`isFeatured\` tinyint NOT NULL DEFAULT 0, \`isVegetarian\` tinyint NOT NULL DEFAULT 0, \`isVegan\` tinyint NOT NULL DEFAULT 0, \`containsGluten\` tinyint NOT NULL DEFAULT 1, \`preparationTimeMinutes\` int NULL, \`categoryId\` int NOT NULL, \`restaurantId\` int NOT NULL, \`averageRating\` float NOT NULL DEFAULT '0', \`ratingCount\` int NOT NULL DEFAULT '0', \`orderCount\` int NOT NULL DEFAULT '0', \`variants\` json NULL, \`addons\` json NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`categories\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(100) NOT NULL, \`description\` text NULL, \`imageUrl\` varchar(255) NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`displayOrder\` int NOT NULL DEFAULT '0', \`parentId\` int NULL, \`restaurantId\` int NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`transactions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`transactionNumber\` varchar(50) NOT NULL, \`userId\` int NOT NULL, \`type\` enum ('deposit', 'withdrawal', 'order', 'refund') NOT NULL, \`amount\` decimal(10,2) NOT NULL, \`direction\` enum ('in', 'out') NOT NULL, \`post_balance\` decimal(10,2) NOT NULL, \`status\` enum ('pending', 'completed', 'rejected') NOT NULL DEFAULT 'pending', \`detail\` text NULL, \`reference_id\` varchar(255) NULL, \`createdAt\` datetime NOT NULL, \`updatedAt\` datetime NOT NULL, \`user_id\` int NULL, UNIQUE INDEX \`IDX_f84391ec65d7cd9f800fa70573\` (\`transactionNumber\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`deposit_withdrawals\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userId\` int NOT NULL, \`amount\` decimal(10,2) NOT NULL, \`type\` enum ('deposit', 'withdrawal') NOT NULL, \`status\` enum ('pending', 'success', 'failed') NOT NULL DEFAULT 'pending', \`payment_id\` varchar(255) NULL, \`transaction_id\` int NULL, \`charge\` decimal(10,2) NOT NULL DEFAULT '0.00', \`after_charge\` decimal(10,2) NOT NULL, \`rate\` varchar(50) NULL, \`payable\` decimal(10,2) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`user_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`order_items\` (\`id\` int NOT NULL AUTO_INCREMENT, \`orderId\` int NULL, \`userId\` int NOT NULL, \`restaurantId\` int NOT NULL, \`foodId\` int NOT NULL, \`foodName\` varchar(255) NULL, \`quantity\` int NOT NULL, \`unitPrice\` decimal(10,2) NOT NULL, \`variants\` json NULL, \`addons\` json NULL, \`notes\` text NULL, \`order_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`coupons\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(100) NOT NULL, \`code\` varchar(50) NOT NULL, \`discount_type\` enum ('percentage', 'fixed') NOT NULL DEFAULT 'percentage', \`discount_value\` decimal(5,2) NOT NULL, \`usage_limit\` int NOT NULL DEFAULT '0', \`used_count\` int NOT NULL DEFAULT '0', \`valid_from\` datetime NOT NULL, \`valid_to\` datetime NOT NULL, \`status\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_e025109230e82925843f2a14c4\` (\`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`orders\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userId\` int NOT NULL, \`restaurantId\` int NULL, \`deliveryId\` int NULL, \`couponId\` int NULL, \`subtotal\` decimal(10,2) NOT NULL, \`vat\` decimal(10,2) NOT NULL DEFAULT '0.00', \`deliveryFee\` decimal(10,2) NOT NULL DEFAULT '0.00', \`discount\` decimal(10,2) NOT NULL DEFAULT '0.00', \`totalPrice\` decimal(10,2) NOT NULL, \`status\` enum ('pending', 'accepted', 'preparing', 'ready_for_pickup', 'delivering', 'completed', 'cancelled', 'expired', 'initialed') NOT NULL DEFAULT 'pending', \`address\` text NOT NULL, \`specialInstructions\` text NULL, \`deliveryAddress\` json NULL, \`street\` text NOT NULL, \`apartment\` text NOT NULL, \`mobile\` text NOT NULL, \`note\` text NOT NULL, \`selfFetch\` tinyint NOT NULL DEFAULT '0', \`location\` int NOT NULL, \`payment\` int NOT NULL, \`paymentType\` enum ('pending', 'paid') NOT NULL DEFAULT 'pending', \`createdAt\` datetime NOT NULL, \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`user_id\` int NULL, \`restaurant_id\` int NULL, \`delivery_id\` int NULL, \`coupon_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(100) NOT NULL, \`username\` varchar(100) NOT NULL, \`email\` varchar(150) NOT NULL, \`phone\` varchar(20) NOT NULL, \`password\` varchar(255) NOT NULL, \`status\` tinyint NOT NULL DEFAULT 1, \`role\` enum ('admin', 'customer', 'restaurant', 'delivery') NOT NULL DEFAULT 'customer', \`description\` text NULL, \`parentId\` int NULL, \`emailVerified\` tinyint NOT NULL DEFAULT 0, \`mobileVerified\` tinyint NOT NULL DEFAULT 0, \`twoFactorEnabled\` tinyint NOT NULL DEFAULT 0, \`kycVerified\` tinyint NOT NULL DEFAULT 0, \`balance\` float NOT NULL DEFAULT '0', \`referralCode\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deliveryAddresses\` json NULL, UNIQUE INDEX \`IDX_fe0bb3f6520ee0469504521e71\` (\`username\`), UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), UNIQUE INDEX \`IDX_a000cca60bcf04454e72769949\` (\`phone\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tickets\` (\`id\` varchar(36) NOT NULL, \`user_id\` int NOT NULL, \`type\` enum ('customer', 'restaurant', 'delivery') NOT NULL DEFAULT 'customer', \`subject\` varchar(255) NOT NULL, \`message\` text NOT NULL, \`status\` enum ('open', 'in_progress', 'closed') NOT NULL DEFAULT 'open', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`payment_gateways\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`config\` json NULL, \`status\` varchar(255) NOT NULL DEFAULT 'inactive', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_d905f911f872997feb55664dd7\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_messages\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`sender_id\` int NULL, \`message\` text NOT NULL, \`status\` enum ('read', 'unread') NOT NULL DEFAULT 'unread', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`login_activity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userId\` int NULL, \`userType\` varchar(10) NOT NULL, \`type\` varchar(255) NOT NULL DEFAULT 'login', \`loginAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`ip\` varchar(255) NULL, \`browser\` varchar(255) NULL, \`device\` varchar(255) NULL, \`os\` varchar(255) NULL, \`details\` varchar(255) NULL, \`adminId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`locations\` ADD CONSTRAINT \`FK_78eda52dc27b7ad20350c4a752d\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`food_items\` ADD CONSTRAINT \`FK_9191ed6ba4b05c67d30d6d32d8a\` FOREIGN KEY (\`categoryId\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`food_items\` ADD CONSTRAINT \`FK_0b5b78bd2257126dff1e653af9e\` FOREIGN KEY (\`restaurantId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD CONSTRAINT \`FK_9a6f051e66982b5f0318981bcaa\` FOREIGN KEY (\`parentId\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD CONSTRAINT \`FK_fe8e7d37475de7eb2f8f83a6da0\` FOREIGN KEY (\`restaurantId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transactions\` ADD CONSTRAINT \`FK_e9acc6efa76de013e8c1553ed2b\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`deposit_withdrawals\` ADD CONSTRAINT \`FK_2b4026614da4637eba86e441868\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`deposit_withdrawals\` ADD CONSTRAINT \`FK_403c844f01b564431506c61e889\` FOREIGN KEY (\`transaction_id\`) REFERENCES \`transactions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_32bee105d7ad0a93778e739f702\` FOREIGN KEY (\`foodId\`) REFERENCES \`food_items\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_a0a49ab9e3ffc13bf70e0c0abc3\` FOREIGN KEY (\`restaurantId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_145532db85752b29c57d2b7b1f1\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_a922b820eeef29ac1c6800e826a\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_85fdda5fcce2f397ef8f117a2c6\` FOREIGN KEY (\`restaurant_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_141cb5f1928caf8b0e77cb8bd66\` FOREIGN KEY (\`delivery_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_6284f0f60e4cb96c12ff96f0f15\` FOREIGN KEY (\`coupon_id\`) REFERENCES \`coupons\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_8110309ac51ed55a91d28625b88\` FOREIGN KEY (\`parentId\`) REFERENCES \`admins\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tickets\` ADD CONSTRAINT \`FK_2e445270177206a97921e461710\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_messages\` ADD CONSTRAINT \`FK_c9caa82a017083ee03444ffecdf\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_messages\` ADD CONSTRAINT \`FK_74adf60fffd02e8c754b882b1d3\` FOREIGN KEY (\`sender_id\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`login_activity\` ADD CONSTRAINT \`FK_28aab163e727fb7ddbb9f07c485\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`login_activity\` ADD CONSTRAINT \`FK_6ab7239f4c14afacea611ea065f\` FOREIGN KEY (\`adminId\`) REFERENCES \`admins\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`login_activity\` DROP FOREIGN KEY \`FK_6ab7239f4c14afacea611ea065f\``);
        await queryRunner.query(`ALTER TABLE \`login_activity\` DROP FOREIGN KEY \`FK_28aab163e727fb7ddbb9f07c485\``);
        await queryRunner.query(`ALTER TABLE \`user_messages\` DROP FOREIGN KEY \`FK_74adf60fffd02e8c754b882b1d3\``);
        await queryRunner.query(`ALTER TABLE \`user_messages\` DROP FOREIGN KEY \`FK_c9caa82a017083ee03444ffecdf\``);
        await queryRunner.query(`ALTER TABLE \`tickets\` DROP FOREIGN KEY \`FK_2e445270177206a97921e461710\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_8110309ac51ed55a91d28625b88\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_6284f0f60e4cb96c12ff96f0f15\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_141cb5f1928caf8b0e77cb8bd66\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_85fdda5fcce2f397ef8f117a2c6\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_a922b820eeef29ac1c6800e826a\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_145532db85752b29c57d2b7b1f1\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_a0a49ab9e3ffc13bf70e0c0abc3\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_32bee105d7ad0a93778e739f702\``);
        await queryRunner.query(`ALTER TABLE \`deposit_withdrawals\` DROP FOREIGN KEY \`FK_403c844f01b564431506c61e889\``);
        await queryRunner.query(`ALTER TABLE \`deposit_withdrawals\` DROP FOREIGN KEY \`FK_2b4026614da4637eba86e441868\``);
        await queryRunner.query(`ALTER TABLE \`transactions\` DROP FOREIGN KEY \`FK_e9acc6efa76de013e8c1553ed2b\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP FOREIGN KEY \`FK_fe8e7d37475de7eb2f8f83a6da0\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP FOREIGN KEY \`FK_9a6f051e66982b5f0318981bcaa\``);
        await queryRunner.query(`ALTER TABLE \`food_items\` DROP FOREIGN KEY \`FK_0b5b78bd2257126dff1e653af9e\``);
        await queryRunner.query(`ALTER TABLE \`food_items\` DROP FOREIGN KEY \`FK_9191ed6ba4b05c67d30d6d32d8a\``);
        await queryRunner.query(`ALTER TABLE \`locations\` DROP FOREIGN KEY \`FK_78eda52dc27b7ad20350c4a752d\``);
        await queryRunner.query(`DROP TABLE \`login_activity\``);
        await queryRunner.query(`DROP TABLE \`user_messages\``);
        await queryRunner.query(`DROP INDEX \`IDX_d905f911f872997feb55664dd7\` ON \`payment_gateways\``);
        await queryRunner.query(`DROP TABLE \`payment_gateways\``);
        await queryRunner.query(`DROP TABLE \`tickets\``);
        await queryRunner.query(`DROP INDEX \`IDX_a000cca60bcf04454e72769949\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_fe0bb3f6520ee0469504521e71\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP TABLE \`orders\``);
        await queryRunner.query(`DROP INDEX \`IDX_e025109230e82925843f2a14c4\` ON \`coupons\``);
        await queryRunner.query(`DROP TABLE \`coupons\``);
        await queryRunner.query(`DROP TABLE \`order_items\``);
        await queryRunner.query(`DROP TABLE \`deposit_withdrawals\``);
        await queryRunner.query(`DROP INDEX \`IDX_f84391ec65d7cd9f800fa70573\` ON \`transactions\``);
        await queryRunner.query(`DROP TABLE \`transactions\``);
        await queryRunner.query(`DROP TABLE \`categories\``);
        await queryRunner.query(`DROP TABLE \`food_items\``);
        await queryRunner.query(`DROP TABLE \`locations\``);
        await queryRunner.query(`DROP INDEX \`IDX_b4585db4f7fe5bdf537bd81861\` ON \`admins\``);
        await queryRunner.query(`DROP INDEX \`IDX_051db7d37d478a69a7432df147\` ON \`admins\``);
        await queryRunner.query(`DROP TABLE \`admins\``);
    }

}
