import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1775808563198 implements MigrationInterface {
    name = 'Init1775808563198'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`role_menus\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`roleId\` int NULL, \`menuId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`menus\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`path\` varchar(255) NOT NULL, \`icon\` varchar(255) NULL, \`sortOrder\` int NOT NULL DEFAULT '0', \`visible\` tinyint NOT NULL, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`parentId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`admin_permissions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`enabled\` tinyint NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`adminId\` int NULL, \`permissionId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`permissions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`key\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, \`description\` text NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`menuId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`role_permissions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`roleId\` int NULL, \`permissionId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`roles\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`description\` varchar(255) NULL, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`admin_menus\` (\`id\` int NOT NULL AUTO_INCREMENT, \`enabled\` tinyint NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`adminId\` int NULL, \`menuId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`system_logs\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userType\` enum ('user', 'admin') NOT NULL, \`action\` varchar(255) NOT NULL, \`targetType\` varchar(255) NOT NULL, \`targetId\` int NULL, \`description\` text NOT NULL, \`ipAddress\` varchar(255) NOT NULL, \`city\` varchar(100) NULL, \`state\` varchar(100) NULL, \`zipCode\` varchar(20) NULL, \`country\` varchar(100) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`adminId\` int NULL, \`userId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`notifications\` (\`id\` int NOT NULL AUTO_INCREMENT, \`title\` varchar(255) NOT NULL, \`content\` text NOT NULL, \`type\` enum ('order', 'user', 'message', 'product', 'category', 'admin', 'cart', 'favorite') NOT NULL, \`path\` text NULL, \`targetId\` int NOT NULL, \`userId\` int NOT NULL, \`userType\` enum ('user', 'admin') NOT NULL, \`enableNoti\` tinyint NOT NULL DEFAULT '0', \`extra\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`admin_notifications\` (\`id\` int NOT NULL AUTO_INCREMENT, \`notificationId\` int NOT NULL, \`adminId\` int NOT NULL, \`isRead\` tinyint NOT NULL DEFAULT '0', \`readAt\` datetime NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`admins\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`email\` varchar(255) NOT NULL, \`password\` text NOT NULL, \`status\` tinyint NOT NULL DEFAULT 1, \`remark\` text NULL, \`referralCode\` varchar(255) NULL, \`city\` varchar(100) NULL, \`state\` varchar(100) NULL, \`zipCode\` varchar(20) NULL, \`country\` varchar(100) NULL, \`ip\` varchar(100) NULL, \`latitude\` varchar(100) NULL, \`longitude\` varchar(100) NULL, \`loginIp\` varchar(100) NULL, \`lastLoginAt\` timestamp NULL, \`twoFactorEnabled\` tinyint NOT NULL DEFAULT '0', \`twoFactorSecret\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`roleId\` int NULL, \`parentId\` int NULL, UNIQUE INDEX \`IDX_051db7d37d478a69a7432df147\` (\`email\`), UNIQUE INDEX \`IDX_b4585db4f7fe5bdf537bd81861\` (\`referralCode\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`locations\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userId\` int NOT NULL, \`address\` text NOT NULL, \`city\` text NOT NULL, \`state\` text NOT NULL, \`postalCode\` text NOT NULL, \`country\` text NOT NULL, \`isPrimary\` tinyint NOT NULL DEFAULT 0, \`receiverName\` text NULL, \`receiverMobile\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`categories\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` text NOT NULL, \`description\` text NULL, \`imageUrl\` varchar(255) NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`displayOrder\` int NOT NULL DEFAULT '0', \`parentId\` int NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`vatPercent\` decimal(5,2) NOT NULL DEFAULT '0.00', \`isCollect\` tinyint NOT NULL DEFAULT 0, \`bgImageUrl\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`favorites\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`userId\` int NULL, \`productId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`carts\` (\`id\` int NOT NULL AUTO_INCREMENT, \`imageUrl\` text NULL, \`quantity\` int NOT NULL DEFAULT '1', \`attributes\` text NULL, \`basePrice\` decimal(10,2) NOT NULL DEFAULT '0.00', \`attrPrice\` decimal(10,2) NOT NULL DEFAULT '0.00', \`unitPrice\` decimal(10,2) NOT NULL DEFAULT '0.00', \`totalPrice\` decimal(10,2) NOT NULL DEFAULT '0.00', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`userId\` int NULL, \`productId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`products\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` text NOT NULL, \`description\` text NULL, \`price\` decimal(10,2) NOT NULL DEFAULT '0.00', \`imageUrl\` text NULL, \`imageList\` text NULL, \`isAvailable\` tinyint NOT NULL DEFAULT 0, \`categoryId\` int NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`attributes\` text NULL, \`attrGroups\` text NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`order_items\` (\`id\` int NOT NULL AUTO_INCREMENT, \`orderId\` int NOT NULL, \`userId\` int NOT NULL, \`productId\` int NULL, \`productName\` text NOT NULL, \`productImage\` text NULL, \`productDesc\` text NULL, \`categoryName\` text NULL, \`quantity\` int NOT NULL DEFAULT '1', \`basePrice\` decimal(10,2) NOT NULL DEFAULT '0.00', \`attrPrice\` decimal(10,2) NOT NULL DEFAULT '0.00', \`unitPrice\` decimal(10,2) NOT NULL DEFAULT '0.00', \`totalPrice\` decimal(10,2) NOT NULL DEFAULT '0.00', \`attributes\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`orders\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userId\` int NOT NULL, \`subtotal\` decimal(10,2) NOT NULL DEFAULT '0.00', \`vat\` decimal(10,2) NOT NULL DEFAULT '0.00', \`deliveryFee\` decimal(10,2) NOT NULL DEFAULT '0.00', \`balanceDeduct\` decimal(10,2) NOT NULL DEFAULT '0.00', \`discountPayPal\` decimal(10,2) NOT NULL DEFAULT '0.00', \`totalPrice\` decimal(10,2) NOT NULL DEFAULT '0.00', \`payAmount\` decimal(10,2) NOT NULL DEFAULT '0.00', \`payMethod\` enum ('stripe', 'paypal', 'balance', 'hybrid', 'card', 'pay2s', 'lemon', 'behalf', 'starpay', 'faf', 'wise') NOT NULL, \`hybridMethod\` enum ('stripe', 'paypal', 'balance', 'hybrid', 'card', 'pay2s', 'lemon', 'behalf', 'starpay', 'faf', 'wise') NOT NULL, \`deliveryMethod\` enum ('standard', 'express') NOT NULL, \`deliveryMethodChanged\` tinyint NOT NULL DEFAULT 0, \`status\` enum ('pending', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded') NOT NULL DEFAULT 'pending', \`userAddress\` text NULL, \`userMobile\` text NULL, \`userName\` text NULL, \`imageUrl\` text NULL, \`quantity\` int NOT NULL, \`paymentStatus\` enum ('pending', 'paid', 'cancelled', 'refunded') NOT NULL DEFAULT 'pending', \`paymentLink\` text NULL, \`shareLink\` text NULL, \`paidAt\` datetime NULL, \`estimatedProcessingAt\` datetime NULL, \`processingAt\` datetime NULL, \`estimatedShippedAt\` datetime NULL, \`shippedAt\` datetime NULL, \`estimatedDeliveredAt\` datetime NULL, \`deliveredAt\` datetime NULL, \`cancelledAt\` datetime NULL, \`refundedAt\` datetime NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`uuid\` text NULL, \`deliveryProofImages\` text NULL, \`paypalResponseRaw\` text NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`transactions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`transactionNumber\` text NULL, \`amount\` decimal(10,2) NOT NULL, \`postBalance\` decimal(10,2) NOT NULL DEFAULT '0.00', \`direction\` enum ('in', 'out') NOT NULL, \`method\` enum ('stripe', 'paypal', 'balance', 'hybrid', 'card', 'pay2s', 'lemon', 'behalf', 'starpay', 'faf', 'wise') NOT NULL, \`hybridMethod\` enum ('stripe', 'paypal', 'balance', 'hybrid', 'card', 'pay2s', 'lemon', 'behalf', 'starpay', 'faf', 'wise') NOT NULL, \`type\` enum ('deposit', 'withdrawal', 'order_payment') NOT NULL, \`status\` enum ('pending', 'completed', 'cancelled', 'refunded') NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`userId\` int NULL, \`orderId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`lucky_wheels\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`prizes\` text NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`events\` (\`id\` int NOT NULL AUTO_INCREMENT, \`template\` enum ('lucky_wheel') NOT NULL, \`name\` varchar(255) NOT NULL, \`type\` enum ('daily_task') NOT NULL, \`remark\` varchar(255) NOT NULL, \`startDate\` timestamp NOT NULL, \`endDate\` timestamp NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`luckyWheelId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`event_logs\` (\`id\` int NOT NULL AUTO_INCREMENT, \`type\` enum ('point') NOT NULL, \`reward\` text NOT NULL, \`isClaim\` tinyint NOT NULL DEFAULT '0', \`claimAt\` timestamp NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`userId\` int NULL, \`eventId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(100) NOT NULL, \`username\` varchar(100) NOT NULL, \`avatar\` text NULL, \`email\` varchar(150) NOT NULL, \`phone\` varchar(20) NOT NULL, \`password\` varchar(100) NOT NULL, \`status\` tinyint NOT NULL DEFAULT 1, \`remark\` text NULL, \`balance\` decimal(10,2) NOT NULL DEFAULT '0.00', \`emailVerified\` tinyint NOT NULL DEFAULT 0, \`mobileVerified\` tinyint NOT NULL DEFAULT 0, \`twoFactorEnabled\` tinyint NOT NULL DEFAULT 0, \`kycVerified\` tinyint NOT NULL DEFAULT 0, \`city\` varchar(100) NULL, \`state\` varchar(100) NULL, \`zipCode\` varchar(20) NULL, \`country\` varchar(100) NULL, \`referralCode\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`mode\` enum ('live', 'test') NOT NULL DEFAULT 'live', \`ip\` varchar(100) NULL, \`latitude\` varchar(100) NULL, \`longitude\` varchar(100) NULL, \`loginIp\` varchar(100) NULL, \`lastLoginAt\` timestamp NULL, \`point\` decimal(10,2) NOT NULL DEFAULT '0.00', \`roleId\` int NULL, \`parentId\` int NULL, UNIQUE INDEX \`IDX_fe0bb3f6520ee0469504521e71\` (\`username\`), UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), UNIQUE INDEX \`IDX_a000cca60bcf04454e72769949\` (\`phone\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`messages\` (\`id\` int NOT NULL AUTO_INCREMENT, \`senderId\` int NOT NULL, \`content\` text NOT NULL, \`isRead\` tinyint NOT NULL DEFAULT '0', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`readAt\` timestamp NULL, \`ticketId\` int NULL, \`senderRoleId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tickets\` (\`id\` int NOT NULL AUTO_INCREMENT, \`subject\` text NOT NULL, \`status\` enum ('opened', 'closed') NOT NULL DEFAULT 'opened', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`userId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`settings\` (\`id\` int NOT NULL AUTO_INCREMENT, \`group\` text NOT NULL, \`key\` text NOT NULL, \`value\` text NOT NULL, \`remark\` text NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`payment_gateways\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(100) NOT NULL, \`currency\` text NULL, \`config\` text NULL, \`status\` enum ('active', 'inactive', 'maintenance') NOT NULL DEFAULT 'inactive', \`feePercent\` decimal(10,2) NOT NULL DEFAULT '0.00', \`feeFixed\` decimal(10,2) NOT NULL DEFAULT '0.00', \`minAmount\` decimal(10,2) NOT NULL DEFAULT '0.00', \`maxAmount\` decimal(10,2) NOT NULL DEFAULT '0.00', \`discount\` decimal(10,2) NOT NULL DEFAULT '0.00', \`sortOrder\` int NOT NULL DEFAULT '0', \`isDefault\` tinyint NOT NULL DEFAULT '0', \`notes\` text NULL, \`notices\` text NULL, \`blackList\` text NULL, \`isManual\` tinyint NOT NULL DEFAULT '1', \`logo\` text NULL, \`images\` text NULL, \`exLogos\` text NULL, \`visible\` tinyint NOT NULL DEFAULT '0', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`providerId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`payment_providers\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(100) NOT NULL, \`code\` varchar(50) NOT NULL, \`type\` enum ('card', 'wallet', 'crypto', 'bank_transfer') NOT NULL, \`remark\` varchar(100) NOT NULL, \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`login_activity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userId\` int NULL, \`userType\` text NOT NULL, \`type\` varchar(50) NOT NULL DEFAULT 'login', \`ip\` varchar(255) NULL, \`browser\` varchar(255) NULL, \`device\` varchar(255) NULL, \`os\` varchar(255) NULL, \`details\` varchar(255) NULL, \`city\` varchar(100) NULL, \`state\` varchar(100) NULL, \`zipCode\` varchar(20) NULL, \`country\` varchar(100) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`adminId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`exchange-rate\` (\`id\` int NOT NULL AUTO_INCREMENT, \`fromCurrency\` varchar(255) NOT NULL, \`toCurrency\` varchar(255) NOT NULL, \`rate\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ip_info\` (\`id\` int NOT NULL AUTO_INCREMENT, \`ip\` varchar(45) NOT NULL, \`network\` varchar(255) NOT NULL, \`version\` varchar(255) NOT NULL, \`city\` varchar(255) NULL, \`region\` varchar(255) NULL, \`region_code\` varchar(255) NULL, \`country\` varchar(255) NOT NULL, \`country_name\` varchar(255) NOT NULL, \`country_code\` varchar(2) NOT NULL, \`country_code_iso3\` varchar(3) NOT NULL, \`country_capital\` varchar(255) NOT NULL, \`country_tld\` varchar(255) NULL, \`continent_code\` varchar(2) NOT NULL, \`in_eu\` tinyint NOT NULL, \`postal\` varchar(255) NULL, \`latitude\` float NOT NULL, \`longitude\` float NOT NULL, \`timezone\` varchar(255) NOT NULL, \`utc_offset\` varchar(255) NOT NULL, \`country_calling_code\` varchar(255) NOT NULL, \`currency\` varchar(255) NOT NULL, \`currency_name\` varchar(255) NOT NULL, \`languages\` varchar(255) NOT NULL, \`country_area\` float NOT NULL, \`country_population\` bigint NOT NULL, \`asn\` varchar(255) NOT NULL, \`org\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_e79b1af8bc707aa105df6ceef7\` (\`ip\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`coupons\` (\`id\` varchar(36) NOT NULL, \`name\` text NOT NULL, \`code\` varchar(100) NOT NULL, \`discount_type\` enum ('percentage', 'fixed') NOT NULL DEFAULT 'percentage', \`discount_value\` decimal(5,2) NOT NULL, \`usage_limit\` int NOT NULL DEFAULT '0', \`used_count\` int NOT NULL DEFAULT '0', \`valid_from\` datetime NOT NULL, \`valid_to\` datetime NOT NULL, \`status\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_e025109230e82925843f2a14c4\` (\`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX \`IDX_e025109230e82925843f2a14c4\` ON \`coupons\``);
        await queryRunner.query(`DROP TABLE \`coupons\``);
        await queryRunner.query(`DROP INDEX \`IDX_e79b1af8bc707aa105df6ceef7\` ON \`ip_info\``);
        await queryRunner.query(`DROP TABLE \`ip_info\``);
        await queryRunner.query(`DROP TABLE \`exchange-rate\``);
        await queryRunner.query(`DROP TABLE \`login_activity\``);
        await queryRunner.query(`DROP TABLE \`payment_providers\``);
        await queryRunner.query(`DROP TABLE \`payment_gateways\``);
        await queryRunner.query(`DROP TABLE \`settings\``);
        await queryRunner.query(`DROP TABLE \`tickets\``);
        await queryRunner.query(`DROP TABLE \`messages\``);
        await queryRunner.query(`DROP INDEX \`IDX_a000cca60bcf04454e72769949\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_fe0bb3f6520ee0469504521e71\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP TABLE \`event_logs\``);
        await queryRunner.query(`DROP TABLE \`events\``);
        await queryRunner.query(`DROP TABLE \`lucky_wheels\``);
        await queryRunner.query(`DROP TABLE \`transactions\``);
        await queryRunner.query(`DROP TABLE \`orders\``);
        await queryRunner.query(`DROP TABLE \`order_items\``);
        await queryRunner.query(`DROP TABLE \`products\``);
        await queryRunner.query(`DROP TABLE \`carts\``);
        await queryRunner.query(`DROP TABLE \`favorites\``);
        await queryRunner.query(`DROP TABLE \`categories\``);
        await queryRunner.query(`DROP TABLE \`locations\``);
        await queryRunner.query(`DROP INDEX \`IDX_b4585db4f7fe5bdf537bd81861\` ON \`admins\``);
        await queryRunner.query(`DROP INDEX \`IDX_051db7d37d478a69a7432df147\` ON \`admins\``);
        await queryRunner.query(`DROP TABLE \`admins\``);
        await queryRunner.query(`DROP TABLE \`admin_notifications\``);
        await queryRunner.query(`DROP TABLE \`notifications\``);
        await queryRunner.query(`DROP TABLE \`system_logs\``);
        await queryRunner.query(`DROP TABLE \`admin_menus\``);
        await queryRunner.query(`DROP TABLE \`roles\``);
        await queryRunner.query(`DROP TABLE \`role_permissions\``);
        await queryRunner.query(`DROP TABLE \`permissions\``);
        await queryRunner.query(`DROP TABLE \`admin_permissions\``);
        await queryRunner.query(`DROP TABLE \`menus\``);
        await queryRunner.query(`DROP TABLE \`role_menus\``);
    }

}
